### ISSUE TITLE
Round-trip D --> J --> D ... is unstable with try-catch block handlers

### ISSUE THREAD

**Issue by Col-E** [Col-E/r8#7]
Converting from Dex to Java to Dex back to Java fails on the `068-classloader` sample.

StackTrace:
```
Caused by: com.android.tools.r8.errors.CompilationError: Different stack heights at jump target: 0 != 1
	at com.android.tools.r8.ir.conversion.CfState.merge(CfState.java:131)
	at com.android.tools.r8.ir.conversion.CfState.merge(CfState.java:126)
	at com.android.tools.r8.ir.conversion.CfSourceCode.recordStateForTarget(CfSourceCode.java:587)
	at com.android.tools.r8.ir.conversion.CfSourceCode.buildInstruction(CfSourceCode.java:567)
	at com.android.tools.r8.ir.conversion.CfSourceCode.buildInstruction(CfSourceCode.java:574)
	at com.android.tools.r8.ir.conversion.IRBuilder.processWorklist(IRBuilder.java:924)
	at com.android.tools.r8.ir.conversion.IRBuilder.build(IRBuilder.java:667)
	at com.android.tools.r8.graph.CfCode.internalBuild(CfCode.java:758)
	at com.android.tools.r8.graph.CfCode.internalBuildPossiblyWithLocals(CfCode.java:664)
	at com.android.tools.r8.graph.CfCode.buildIR(CfCode.java:613)
	at com.android.tools.r8.graph.ProgramMethod.buildIR(ProgramMethod.java:38)
	at com.android.tools.r8.graph.ProgramMethod.buildIR(ProgramMethod.java:32)
	at com.android.tools.r8.ir.conversion.IRConverter.rewriteDesugaredCodeInternal(IRConverter.java:494)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.rewriteNonDesugaredCodeInternal(PrimaryD8L8IRConverter.java:383)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.lambda$rewriteNonDesugaredCode$4(PrimaryD8L8IRConverter.java:368)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.rewriteNonDesugaredCode(PrimaryD8L8IRConverter.java:364)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertMethod(PrimaryD8L8IRConverter.java:165)
	at com.android.tools.r8.ir.conversion.D8MethodProcessor.processMethod(D8MethodProcessor.java:164)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertMethods(PrimaryD8L8IRConverter.java:130)
	at com.android.tools.r8.ir.conversion.ClassConverter.convertMethods(ClassConverter.java:227)
	at com.android.tools.r8.ir.conversion.ClassConverter$DefaultClassConverter.convertClass(ClassConverter.java:245)
	at com.android.tools.r8.ir.conversion.ClassConverter.lambda$internalConvertClasses$2(ClassConverter.java:162)
	at com.android.tools.r8.utils.ThreadUtils.lambda$processItems$5(ThreadUtils.java:106)
	at com.android.tools.r8.utils.ThreadUtils.processItems(ThreadUtils.java:120)
	at com.android.tools.r8.utils.ThreadUtils.processItems(ThreadUtils.java:106)
	at com.android.tools.r8.ir.conversion.ClassConverter.internalConvertClasses(ClassConverter.java:160)
	at com.android.tools.r8.ir.conversion.ClassConverter.convertClasses(ClassConverter.java:66)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertClasses(PrimaryD8L8IRConverter.java:295)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convert(PrimaryD8L8IRConverter.java:69)
	... 22 more
```

The output of multiple round-trip passes is expected to be lossy, but not outright fail.

**Comment by Col-E** [comment]
Say you have some Java class with a method like:
```java
public static void foo(int i) {
	try {
		if (i > 0)
			throw new IOException();
	} catch (IOException e) {
		System.out.println("fail");
	}
}
```
Disassembled:
```java
stack=2, locals=2, args_size=1
  // try {
   0: iload_0
   1: ifle          24
   4: new           #2 // class java/io/IOException
   7: dup
   8: invokespecial #3 // Method java/io/IOException."<init>":()V
  11: athrow
  // } catch {
  15: astore_1
  16: getstatic     #4 // Field java/lang/System.out:Ljava/io/PrintStream;
  19: ldc           #5 // String i > 0
  21: invokevirtual #6 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
  // }
  24: return
Exception table:
   from    to  target type
       0    12    15   Class java/io/IOException
```
If you convert this class to `DEX` then back into JVM bytecode the method then looks like _(Using R8's built in code disassembler)_
```java
.limit stack 2
.limit locals 1
.catch java/io/IOException from L0 to L1 using L1
 0:   iload 0
 1:   ifgt L0
 2:   goto L2
 3: L0: ; locals: 
 5:   new Ljava/io/IOException;
 6:   dup
 8:   invokespecial Ljava/io/IOException;<init>()V
10:   athrow
11: L1: ; locals: 
//   ???????????????? Missing astore, not even represented as a pop either
12:   ; frame: [] []
13:   getstatic Ljava/lang/System;out:Ljava/io/PrintStream; Ljava/io/PrintStream;
// 14:   astore 0
// 15:   aload 0
16:   ldc "fail"
17:   invokevirtual Ljava/io/PrintStream;println(Ljava/lang/String;)V
18: L2: ; locals: 
19:   ; frame: [] []
20:   return
```
Investigating how we get this, I took a look at the `IRCode` of the method.
```c
blocks:
block 0, pred-counts: 0, succ-count: 2, filled: true, sealed: true
predecessors: -
successors: 1 2  (no try/catch successors)
no phis
 #0: -1: Argument             v0 <- 
   : -1: If                   v0 GTZ block 1 (fallthrough 2)

block 1, pred-counts: 1, succ-count: 2, filled: true, sealed: true
predecessors: 0 
successors: 3* 4  (1 try/catch successors)
no phis
 #0: -1: NewInstance          v1 <-  java.io.IOException
   : -1: Goto                 block 4

block 2, pred-counts: 1, succ-count: 1, filled: true, sealed: true
predecessors: 0 
successors: 5  (no try/catch successors)
no phis
 #0: -1: Goto                 block 5

block 3, pred-counts: 1, succ-count: 1, filled: true, sealed: true
predecessors: 1 
successors: 6  (no try/catch successors)
no phis
 #0: -1: Goto                 block 6

block 4, pred-counts: 1, succ-count: 2, filled: true, sealed: true
predecessors: 1 
successors: 7* 8  (1 try/catch successors)
no phis
 #0: -1: Invoke-Direct        v1; method: void java.io.IOException.<init>()
   : -1: Goto                 block 8

block 5, pred-counts: 2, succ-count: 0, filled: true, sealed: true
predecessors: 2 6 
successors: -
no phis
 #0: -1: Return               

block 6, pred-counts: 3, succ-count: 1, filled: true, sealed: true
predecessors: 3 7 9 
successors: 5  (no try/catch successors)
no phis
 #0: -1: StaticGet            v2 <- ; field: java.io.PrintStream java.lang.System.out
   : -1: ConstString          v3 <-  "fail"
   : -1: Invoke-Virtual       v2, v3; method: void java.io.PrintStream.println(java.lang.String)
   : -1: Goto                 block 5

block 7, pred-counts: 1, succ-count: 1, filled: true, sealed: true
predecessors: 4 
successors: 6  (no try/catch successors)
no phis
 #0: -1: Goto                 block 6

block 8, pred-counts: 1, succ-count: 1, filled: true, sealed: true
predecessors: 4 
successors: 9*  (1 try/catch successors)
no phis
 #0: -1: Throw                v1

block 9, pred-counts: 1, succ-count: 1, filled: true, sealed: true
predecessors: 8 
successors: 6  (no try/catch successors)
no phis
 #0: -1: Goto                 block 6
```
Take a look at block 6, which represents the catch handler. None of its predecessors refer to it as a `try/catch` successor. Only blocks 1, 4, and 8 declare `try/catch` successors. This represents the `throw new IOException()` portion of the code. We lost the `if (i  >0)` being part of the `try`. 

When the `IOException` throwing is handled:
- block 1 goes to block 3
- block 4 goes to block 7
- block 8 goes to block 8

Block 3, 7, and 8 are just `Goto block 6` duplicated in each. They do not carry the catch behavior, so block 6 is never aware its being referenced as a catch handler.
